Like_function
yu8ta8ro/protospace pull request #13
Opened 2016-11-03 16:42 UTC by yu8ta8ro

# What 
  Like機能の追加

# Why
  Likeをつけられるようにするため

2016-11-05 12:11 UTC, hc0208 requested changes

2016-11-05 12:11 UTC, hc070208 commented on app/controllers/likes_controller.rb
> +    @likes = Like.where(prototype_id: params[:prototype_id])
@likesはviewで使ってる？使わないんだったらいらないね。

2016-11-05 12:11 UTC, hc070208 commented on app/controllers/likes_controller.rb
> +    @likes = Like.where(prototype_id: params[:prototype_id])
これもね。

2016-11-05 12:11 UTC, hc070208 commented on app/views/likes/destroy.js.erb
> +$("#like").html("<%= j(render "likes/likes") %>");
これちゃんと動いてる？
gif貼って

2016-11-05 12:11 UTC, hc070208 commented on app/views/prototypes/_prototype.html.haml
> +    = link_to image_tag("sample.png"), prototype_path(prototype.id)
sample.pngは変えといて

2016-11-05 12:11 UTC, hc070208 commented on app/views/prototypes/_prototype.html.haml
> +          / %a{href: "#"} by #{prototype.user.name}
ユーザーネーム表示させて

2016-11-05 12:11 UTC, hc070208 commented on app/controllers/likes_controller.rb
> +    @prototypes = Prototype.all
@prototypesっていらないよね

2016-11-05 12:11 UTC, hc070208 commented on app/controllers/likes_controller.rb
> +    @prototypes = Prototype.all
これも

2016-11-17 05:13 UTC, yu8ta8ro commented on app/views/likes/destroy.js.erb
> +$("#like").html("<%= j(render "likes/likes") %>");
![image](https://cloud.githubusercontent.com/assets/17869139/20377109/03811d30-acd0-11e6-93df-26f206954c31.png)

2016-11-17 05:23 UTC, yu8ta8ro commented on app/views/likes/destroy.js.erb
> +$("#like").html("<%= j(render "likes/likes") %>");
![like](https://cloud.githubusercontent.com/assets/17869139/20377277/73c4cb22-acd1-11e6-9814-f7211d2dbae8.gif)

2016-11-17 05:32 UTC, yu8ta8ro commented on app/controllers/likes_controller.rb
> +    @prototypes = Prototype.all
likeを数える時に使うのでそのままにしています！

2016-11-17 05:32 UTC, yu8ta8ro commented on app/controllers/likes_controller.rb
> +    @prototypes = Prototype.all
入りませんでした！

2016-11-17 05:43 UTC, yu8ta8ro commented on app/views/prototypes/_prototype.html.haml
> +    = link_to image_tag("sample.png"), prototype_path(prototype.id)
変えました！

2016-11-17 05:43 UTC, yu8ta8ro commented on app/views/prototypes/_prototype.html.haml
> +          / %a{href: "#"} by #{prototype.user.name}
コメントアウト解除しました！

2016-11-17 11:35 UTC, hc070208 commented
動いてるとこみたいな！gifで貼って欲しい

2016-11-18 03:48 UTC, yu8ta8ro commented
![like](https://cloud.githubusercontent.com/assets/17869139/20418028/441de07c-ad8d-11e6-9c53-7883464b8a94.gif)

2016-11-19 03:09 UTC, hc0208 requested changes

2016-11-19 03:09 UTC, hc070208 commented on app/controllers/prototypes_controller.rb
> +    @prototype = current_user.prototypes.create(create_params)
current_user.prototypes.newだね

2016-11-22 15:21 UTC, yu8ta8ro commented on app/controllers/prototypes_controller.rb
> +    @prototype = current_user.prototypes.create(create_params)
修正しました！

2016-11-23 14:37 UTC, hc070208 commented
LGTM

2016-11-23 14:38 UTC, merged