comment_function1
yu8ta8ro/protospace pull request #14
Opened 2016-11-23 18:11 UTC by yu8ta8ro

# What
 コメント機能の実装

# Why
 ユーザーがコメントできるようにするため。

2016-11-24 04:52 UTC, hc0208 requested changes

2016-11-24 04:52 UTC, hc070208 commented on app/controllers/comments_controller.rb
> +    current_user.comments.create(comment_params)
prototypeと同じようにバリデーションかけて成功した時と失敗した時とで処理を分けよう

2016-12-02 20:02 UTC, yu8ta8ro commented on app/controllers/comments_controller.rb
> +    current_user.comments.create(comment_params)
空白ではコメントできないように、required: trueを追加しました。

2016-12-02 23:51 UTC, hc070208 commented on app/controllers/comments_controller.rb
> +    current_user.comments.create(comment_params)
ずるw

2016-12-02 23:51 UTC, hc070208 commented
LGTM

2016-12-03 00:33 UTC, merged