added carriewave
yu8ta8ro/protospace pull request #9
Opened 2016-06-30 14:29 UTC by yu8ta8ro

# What
 プロトタイプ投稿機能の実装。
# Why
 プロトタイプを投稿できるようにするため。

2016-06-30 18:18 UTC, hc070208 commented on app/controllers/prototypes_controller.rb
> +    Prototype.create(catch_copy: create_params[:catch_copy], title: create_params[:title], concept: create_params[:concept], user_id: current_user.id)
private以下にまとめよう

2016-06-30 18:18 UTC, hc070208 commented on app/controllers/prototypes_controller.rb
> +    @prototypes = Prototype.all
新着順に直そう

2016-06-30 18:19 UTC, hc070208 commented on app/views/prototypes/index.html.haml
> +    - @prototypes.each do |prototype|
部分テンプレートにしたほうが使い回しできるから部分テンプレートで

2016-06-30 18:19 UTC, hc070208 commented on app/views/prototypes/index.html.haml
> +          %a{href: "/prototypes/show"}
link_toにしてpath指定で

2016-06-30 18:21 UTC, hc070208 commented
画像も投稿できるようにしよう！

2016-09-27 14:11 UTC, yu8ta8ro commented on app/controllers/prototypes_controller.rb
> +    Prototype.create(catch_copy: create_params[:catch_copy], title: create_params[:title], concept: create_params[:concept], user_id: current_user.id)
paramsをprivateの下にまとめました！

2016-09-27 14:11 UTC, yu8ta8ro commented on app/controllers/prototypes_controller.rb
> +    @prototypes = Prototype.all
コードを付け加えました！

2016-09-27 14:12 UTC, yu8ta8ro commented on app/views/prototypes/index.html.haml
> +    - @prototypes.each do |prototype|
_prototype.html.haml、部分テンプレートを作りました

2016-09-27 14:12 UTC, yu8ta8ro commented on app/views/prototypes/index.html.haml
> +          %a{href: "/prototypes/show"}
なんども申し訳ありません！以後気をつけます

2016-09-27 14:19 UTC, hc0208 requested changes

2016-09-27 14:19 UTC, hc070208 commented on app/controllers/prototypes_controller.rb
> +    Prototype.create(catch_copy: create_params[:catch_copy], title: create_params[:title], concept: create_params[:concept], user_id: current_user.id)
引数はcreate_paramsだけで行きたいね。

2016-09-27 14:19 UTC, hc070208 commented on app/controllers/prototypes_controller.rb
> +    Prototype.create(catch_copy: create_params[:catch_copy], title: create_params[:title], concept: create_params[:concept], user_id: current_user.id)
バリデーションに引っかかった時にエラーが出るようにしたいね。

2016-09-27 14:19 UTC, hc070208 commented on app/models/prototype_image.rb
> +  # validates :prototype_id
コメントアウトは消しとこうか

2016-09-27 14:19 UTC, hc070208 commented on app/views/prototypes/index.html.haml
> +    - @prototypes.each do |prototype|
部分テンプレートにしたらeach使わなくても書けるからその書き方で書こう

2016-09-27 14:19 UTC, hc070208 commented on app/views/prototypes/new.html.haml
> +/   = addresses_form.label :tel, "電話番号"
このあたりも消しとこう

2016-10-14 05:01 UTC, yu8ta8ro commented on app/models/prototype_image.rb
> +  # validates :prototype_id
create_params にまとめました！
バリデーションのエラーメッセージも出しました！！

2016-10-14 05:02 UTC, yu8ta8ro commented on app/views/prototypes/new.html.haml
> +/   = addresses_form.label :tel, "電話番号"
renderのオプションを付け加えました！

2016-10-14 05:12 UTC, hc0208 requested changes

2016-10-14 05:12 UTC, hc070208 commented on app/views/prototypes/index.html.haml
> +          - link_to new_prototype_path, "Newest PROTO"
「-」じゃなくて「=」かな

2016-10-14 05:12 UTC, hc070208 commented on app/controllers/prototypes_controller.rb
> +    params.require(:prototype).permit(:catch_copy, :title, :concept, :user_id, prototype_images_attributes: [:id, :content, :content_type, :prototype_id])
見にくいからいい感じに改行してほしい。

2016-10-15 02:09 UTC, yu8ta8ro commented on app/views/prototypes/index.html.haml
> +          - link_to new_prototype_path, "Newest PROTO"
訂正しました！

2016-10-15 02:09 UTC, yu8ta8ro commented on app/controllers/prototypes_controller.rb
> +    params.require(:prototype).permit(:catch_copy, :title, :concept, :user_id, prototype_images_attributes: [:id, :content, :content_type, :prototype_id])
カンマの後に改行入れました

2016-10-22 04:07 UTC, hc070208 commented
LGTM

2016-10-24 11:07 UTC, merged